appName: "roommate"
env: "local"

frontend:
  name: roommate-frontend
  deployment:
    strategy: Recreate
    replicas: 2
    containerName: frontend
    containerImage: grae888/roommate-frontend
    containerPorts:
      - name: http
        containerPort: 80
    cpuMin: 100m
    cpuMax: 300m
    memMin: 128Mi
    memMax: 256Mi
    storageMin: 100Mi
    storageMax: 1Gi
  service:
    type: NodePort
    ports:
      - name: http
        port: 80
        targetPort: 80
        nodePort: 30080