appName: "roommate"
env: "prod"

frontend:
  name: roommate-frontend
  deployment:
    strategy: RollingUpdate
    replicas: 2
    containerName: frontend
    containerImage: grae888/roommate-frontend
    containerPorts:
      - name: http
        containerPort: 80
    cpuMin: 100m
    cpuMax: 600m
    memMin: 128Mi
    memMax: 512Mi
    storageMin: 100Mi
    storageMax: 2Gi
  service:
    type: ClusterIP
    ports:
      - name: http
        port: 80
        targetPort: 80
  ingress:
    paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: roommate-service
            port:
              number: 80
    certificateArn: ""
    cognito:
      userPoolArn: ""
      userPoolClientId: ""
      userPoolDomainPrefix: ""