appName: "roommate"

frontend:
  name: roommate-frontend
  deployment:
    strategy: RollingUpdate
    replicas: 2
    containerName: nginx-app
    containerImage: nginx:latest
    containerPorts:
      - name: http
        containerPort: 80
    cpuMin: 100m
    cpuMax: 600m
    memMin: 128Mi
    memMax: 512Mi
    storageMin: 100Mi
    storageMax: 2Gi
  service:
    ports:
      - name: http
        port: 80
        targetPort: 80
  ingress:
    paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: roommate-service
            port:
              number: 80