appName: "roommate"

frontend:
  name: roommate-frontend
  deployment:
    strategy: Recreate
    replicas: 2
    containerName: nginx-app
    containerImage: nginx:latest
    containerPorts:
      - name: http
        containerPort: 80
        protocol: TCP
    cpuMin: 100m
    cpuMax: 300m
    memMin: 128Mi
    memMax: 256Mi
    storageMin: 100Mi
    storageMax: 1Gi
  service:
    ports:
      - name: http
        port: 80
        targetPort: 80
        protocol: TCP