apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: {{ .Values.nodeClass.name }}
spec:
  role: {{ .Values.nodeRole }}
  amiSelectorTerms:
    - alias: {{ .Values.nodeClass.amiAlias }}
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: {{ .Values.appName }}
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: {{ .Values.appName }}