appName: ""
nodeRole: ""

nodeClass:
  name: default
  amiAlias: al2023@latest

nodePool:
  name: default
  capacityTypes:
    - spot
  architectures:
    - amd64
  instanceCategories:
    - t
  cpuLimit: 8
  memLimit: 16Gi
  consolidationPolicy: WhenEmptyOrUnderutilized
  consolidateAfter: 1m