apiVersion: v1
kind: Service
metadata:
    name: {{ .Values.redis.name }}-service
    labels:
        app: {{ .Values.redis.name }}
spec:
    type: {{ .Values.redis.service.type }}
    selector:
        app: {{ .Values.redis.name }}
    ports:
{{- toYaml .Values.redis.service.ports | nindent 8 }}