name: deploy to aws

on:
  push:
    branches: [main]
    paths:
      - "infra/cfn/networking.yaml"
      - ".github/workflows/deploy-networking-cfn.yml"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    env:
      AWS_REGION: ap-southeast-2
      STACK_NAME: eks-networking

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: validate cfn
        run: |
          aws cloudformation validate-template \
            --template-body file://infra/cfn/networking.yaml

      - name: deploy cfn
        run: |
          aws cloudformation deploy \
            --stack-name "${STACK_NAME}" \
            --template-file infra/cfn/networking.yaml \
            --region "${AWS_REGION}" \
            --no-fail-on-empty-changeset \
            --capabilities CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND
