name: validate cloudformation

on:
  pull_request:
    branches:
      - main
    paths:
      - "infra/cfn/**"
  workflow_dispatch:

permissions:
    id-token: write
    contents: read

jobs:
  validate-cloudformation:
    runs-on: ubuntu-latest
    environment: production

    env:
        AWS_REGION: ap-southeast-2
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: validate networking.yaml
        run: |
            echo "validating infra/cfn/networking.yaml..."
            aws cloudformation validate-template --template-body file://infra/cfn/networking.yaml
  
      - name: validate eks.yaml
        run: |
            echo "validating infra/cfn/eks.yaml..."
            aws cloudformation validate-template --template-body file://infra/cfn/eks.yaml